kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.14
    commands:
      - cd pkg/linenotify
      - go test

  - name: build
    image: golang:1.14
    commands:
      - cd cmd/linenotify
      - export CGO_ENABLED=0
      - go build

  - name: post
    image: alpine:3.12.0
    environment:
      LINE_NOTIFY_TOKEN:
        from_secret: line_notify_token
    commands:
      - ./cmd/linenotify/linenotify status
      - ./cmd/linenotify/linenotify notifymessage "drone test"
      - ./cmd/linenotify/linenotify notifyimage "drone test" test/test.png
